# Generated by Django 3.0.6 on 2021-07-04 21:48

import colorfield.fields
import common.models.picture
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import posts.models.post
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=common.models.picture.picture)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, default='#42a5f5', max_length=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=posts.models.post.picture)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='posts.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
