# Generated by Django 3.0.6 on 2021-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
