# Generated by Django 3.0.6 on 2021-07-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210705_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hashtag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_hashtag', to='posts.Hashtag'),
            preserve_default=False,
        ),
    ]
