# Generated by Django 3.0.6 on 2021-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210705_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='common-slug', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='common-slug', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
