# Generated by Django 3.0.6 on 2021-07-29 08:40

from django.db import migrations, models
import django_resized.forms
import posts.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210706_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_og_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[512, 512], upload_to=posts.models.post.picture),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
