# Generated by Django 3.0.6 on 2021-07-14 09:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_img_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
